DROP INDEX [ClusteredColumnStoreIndex-20160603-115211] ON
[dbo].FACT_MEASURE_ICT WITH ( ONLINE = OFF )
GO

CREATE UNIQUE CLUSTERED INDEX [IX_FACT_MEASURE_ICT] ON
[dbo].[FACT_MEASURE_ICT]
(
[Id]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

SELECT * FROM sys.partitions
WHERE OBJECT_NAME(OBJECT_ID)='FACT_MEASURE_ICT';
GO

--------------------------------------------------------------------------------------------------

DROP INDEX [ClusteredColumnStoreIndex-20160603-133131] ON
[dbo].FACT_MEASURE_SWITCH_APF WITH ( ONLINE = OFF )
GO

CREATE UNIQUE CLUSTERED INDEX [IX_FACT_MEASURE_SWITCH_APF] ON
[dbo].[FACT_MEASURE_SWITCH_APF]
(
[ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

--------------------------------------------------------------------------------------------------

DROP INDEX [ClusteredColumnStoreIndex-20160603-115826] ON
[dbo].FACT_MEASURE_SWITCH_EOL WITH ( ONLINE = OFF )
GO

CREATE UNIQUE CLUSTERED INDEX [IX_FACT_MEASURE_SWITCH_EOL] ON
[dbo].[FACT_MEASURE_SWITCH_EOL]
(
[ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

--------------------------------------------------------------------------------------------------

DROP INDEX [ClusteredColumnStoreIndex-20160603-133208] ON
[dbo].FACT_MEASURE_SWITCH_ICT WITH ( ONLINE = OFF )
GO

CREATE UNIQUE CLUSTERED INDEX [IX_FACT_MEASURE_SWITCH_ICT] ON
[dbo].[FACT_MEASURE_SWITCH_ICT]
(
[ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO

--------------------------------------------------------------------------------------------------

DROP INDEX [ClusteredColumnStoreIndex-20160527-121742] ON
[dbo].FACT_MEASURE_EOL WITH ( ONLINE = OFF )
GO

CREATE UNIQUE CLUSTERED INDEX [IX_FACT_MEASURE_SWITCH_EOL] ON
[dbo].[FACT_MEASURE_EOL]
(
[ID]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF,
SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF,
DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON)
ON [PRIMARY]
GO