USE [DMCapabiliteRetest]
GO

/****** Object:  Table [dbo].[STATS]    Script Date: 07/07/2016 10:20:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAP_STATION](
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	STATION_ID nvarchar(50) NOT NULL
) ON [PRIMARY]
GO

CREATE TABLE dbo.CAP_SOCKET(
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	TEST_SOCKET_INDEX int NOT NULL,
	CAP_STATION_ID bigint NOT NULL,
	CONSTRAINT fk_cap_station FOREIGN KEY (CAP_STATION_ID) references CAP_STATION(ID)
) ON [PRIMARY]
GO

CREATE TABLE dbo.CAP_NIP_MIC(
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	BATCH_SERIAL_NUMBER nvarchar(10) NOT NULL,
	CAP_SOCKET_ID bigint NOT NULL,
	CONSTRAINT fk_cap_socket FOREIGN KEY (CAP_SOCKET_ID) references CAP_SOCKET(ID)
) ON [PRIMARY]
GO

CREATE TABLE dbo.CAP_STEP_NAME(
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	STEP_NAME nvarchar(255) NOT NULL,
	NAME nvarchar(255) NOT NULL,
	HIGH_LIMIT float NOT NULL,
	LOW_LIMIT float NOT NULL,
	CAP_NIP_MIC_ID bigint NOT NULL,
	CONSTRAINT fk_cap_nic_mic FOREIGN KEY (CAP_NIP_MIC_ID) references CAP_NIP_MIC(ID)
) ON [PRIMARY]
GO

CREATE TABLE dbo.CAP_SERIAL_NUMBER(
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	UUT_SERIAL_NUMBER nvarchar(50) NOT NULL,,
	START_DATE_TIME datetime NOT NULL,
	CAP_NIP_MIC_ID bigint NOT NULL,
	CONSTRAINT fk_cap_nic_mic2 FOREIGN KEY (CAP_NIP_MIC_ID) references CAP_NIP_MIC(ID)
) ON [PRIMARY]
GO

CREATE TABLE dbo.CAP_DATA(
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	DATA float NOT NULL,
	CAP_SERIAL_NUMBER_ID bigint NOT NULL,
	CAP_STEP_NAME_ID bigint NOT NULL,
	CONSTRAINT fk_cap_serial_number FOREIGN KEY (CAP_SERIAL_NUMBER_ID) references CAP_SERIAL_NUMBER(ID),
	CONSTRAINT fk_cap_step_name FOREIGN KEY (CAP_STEP_NAME_ID) references CAP_STEP_NAME(ID),
	CONSTRAINT fk_cap_stats FOREIGN KEY (CAP_STATS_ID) references CAP_STATS(ID)
) ON [PRIMARY]
GO

CREATE TABLE dbo.CAP_STATS(
	ID bigint PRIMARY KEY IDENTITY(1,1) NOT NULL,
	CP float NOT NULL,
	CPK float NOT NULL,
	STD_DEVIATION float NOT NULL,
	CPK1 float NOT NULL,
	CPK2 float NOT NULL
) ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20160707-112325] ON [dbo].[CAP_STATION]
(
	[ID] ASC
)
INCLUDE ( 	[STATION_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-20160707-112359] ON [dbo].[CAP_SOCKET]
(
	[ID] ASC
)
INCLUDE ( 	[TEST_SOCKET_INDEX],
	[CAP_STATION_ID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

