SELECT        
		LTRIM(RTRIM(UUT_RESULT_TEMP.STATION_ID)) AS STATION_ID, 
		LTRIM(RTRIM(UUT_RESULT_TEMP.BATCH_SERIAL_NUMBER)) AS BATCH_SERIAL_NUMBER, 
		LTRIM(RTRIM(UUT_RESULT_TEMP.UUT_SERIAL_NUMBER)) AS UUT_SERIAL_NUMBER, 
		UUT_RESULT_TEMP.TEST_SOCKET_INDEX, 
        LTRIM(RTRIM(UUT_RESULT_TEMP.USER_LOGIN_NAME)) AS USER_LOGIN_NAME, 
		UUT_RESULT_TEMP.START_DATE_TIME, 
		UUT_RESULT_TEMP.EXECUTION_TIME, 
		LTRIM(RTRIM(UUT_RESULT_TEMP.UUT_STATUS)) AS UUT_STATUS, 
		UUT_RESULT_TEMP.UUT_ERROR_CODE, 
        LTRIM(RTRIM(UUT_RESULT_TEMP.UUT_ERROR_MESSAGE)) AS UUT_ERROR_MESSAGE, 
		STEP_RESULT_TEMP.STEP_PARENT, 
		STEP_RESULT_TEMP.ORDER_NUMBER AS STEP_ORDER_NUMBER, 
		LTRIM(RTRIM(STEP_RESULT_TEMP.STEP_NAME)) AS STEP_NAME, 
        LTRIM(RTRIM(STEP_RESULT_TEMP.STEP_TYPE)) AS STEP_TYPE,
		LTRIM(RTRIM(STEP_SEQCALL_TEMP.SEQUENCE_NAME)) AS SEQUENCE_NAME, 
		LTRIM(RTRIM(STEP_SEQCALL_TEMP.SEQUENCE_FILE_PATH)) AS SEQUENCE_FILE_PATH, 
		LTRIM(RTRIM(STEP_RESULT_TEMP.STEP_GROUP)) AS STEP_GROUP, 
		STEP_RESULT_TEMP.STEP_INDEX, 
		LTRIM(RTRIM(STEP_RESULT_TEMP.STEP_ID)) AS STEP_ID, 
		LTRIM(RTRIM(STEP_RESULT_TEMP.[STATUS])) AS STEP_STATUS, 
        LTRIM(RTRIM(STEP_RESULT_TEMP.REPORT_TEXT)) AS REPORT_TEXT, 
		STEP_RESULT_TEMP.ERROR_CODE, 
		LTRIM(RTRIM(STEP_RESULT_TEMP.[ERROR_MESSAGE])) AS [ERROR_MESSAGE], 
		STEP_RESULT_TEMP.CAUSED_SEQFAIL, 
		STEP_RESULT_TEMP.MODULE_TIME, 
		STEP_RESULT_TEMP.TOTAL_TIME, 
		STEP_RESULT_TEMP.NUM_LOOPS, 
		STEP_RESULT_TEMP.NUM_PASSED, 
		STEP_RESULT_TEMP.NUM_FAILED, 
		STEP_RESULT_TEMP.ENDING_LOOP_INDEX, 
        STEP_RESULT_TEMP.LOOP_INDEX,
		PROP_RESULT_TEMP.PROP_PARENT, 
        PROP_RESULT_TEMP.ORDER_NUMBER AS PROP_ORDER_NUMBER, 
		LTRIM(RTRIM(PROP_RESULT_TEMP.NAME)) AS NAME, 
		LTRIM(RTRIM(PROP_RESULT_TEMP.[PATH])) AS [PATH], 
		PROP_RESULT_TEMP.CATEGORY, 
		PROP_RESULT_TEMP.TYPE_VALUE, 
        LTRIM(RTRIM(PROP_RESULT_TEMP.[TYPE_NAME])) AS [TYPE_NAME], 
		LTRIM(RTRIM(PROP_RESULT_TEMP.DISPLAY_FORMAT)) AS DISPLAY_FORMAT, 
		LTRIM(RTRIM(PROP_RESULT_TEMP.DATA)) AS DATA,
		LTRIM(RTRIM(PROP_NUMERICLIMIT_TEMP.COMP_OPERATOR)) AS COMP_OPERATOR, 
		PROP_NUMERICLIMIT_TEMP.HIGH_LIMIT,  
		PROP_NUMERICLIMIT_TEMP.LOW_LIMIT, 
        LTRIM(RTRIM(PROP_NUMERICLIMIT_TEMP.UNITS)) AS UNITS,
		LTRIM(RTRIM(PROP_NUMERICLIMIT_TEMP.[STATUS])) AS PROP_STATUS
FROM            
		UUT_RESULT_TEMP INNER JOIN
        STEP_RESULT_TEMP LEFT OUTER JOIN
        PROP_RESULT_TEMP ON STEP_RESULT_TEMP.ID = PROP_RESULT_TEMP.STEP_RESULT LEFT OUTER JOIN
        PROP_NUMERICLIMIT_TEMP ON PROP_RESULT_TEMP.ID = PROP_NUMERICLIMIT_TEMP.PROP_RESULT ON UUT_RESULT_TEMP.ID = STEP_RESULT_TEMP.UUT_RESULT LEFT OUTER JOIN
        STEP_SEQCALL_TEMP ON STEP_RESULT_TEMP.ID = STEP_SEQCALL_TEMP.STEP_RESULT

--WHERE
		--PROP_NUMERICLIMIT_TEMP.COMP_OPERATOR LIKE 'GELE' 
		--STEP_TYPE LIKE 'SequenceCall'