-- Pass an array into a SQL Server stored procedure
	CREATE TYPE dbo.StationIdList AS TABLE
	(
		StationId nvarchar(50)
	);
	GO

-------------------------------------------------------------------------------------

USE [DMCapabiliteRetest]
GO
/****** Object:  StoredProcedure [dbo].[GetStepNames]    Script Date: 23/05/2016 14:17:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[GetStepNames] @uutSerialNumber nvarchar(10), @stationId nvarchar(50), @startDateTime nvarchar(10), @endDateTime nvarchar(10)
AS
BEGIN
	SET NOCOUNT ON;

	-- Temp table to hold intermediate result
	CREATE TABLE dbo.#FACT_MEASURE_TEMP (
		 STATION_ID nvarchar(255),
		 STEP_NAME nvarchar(255),
		 UUT_SERIAL_NUMBER nvarchar(255),
		 START_DATE_TIME datetime, 		
		 HIGH_LIMIT float,
		 DATA float,
		 LOW_LIMIT float,
		 STATUS nvarchar(255),
		 TOTAL_TIME float,
		 COMP_OPERATOR nvarchar(32)
	);

	-- First part of the query
	INSERT INTO dbo.#FACT_MEASURE_TEMP
		( 
			STATION_ID,
			STEP_NAME,
			UUT_SERIAL_NUMBER,
			START_DATE_TIME,
			HIGH_LIMIT,
			DATA,
			LOW_LIMIT,
			STATUS,
			TOTAL_TIME,
			COMP_OPERATOR
		)
	SELECT 
		LTRIM(RTRIM(STATION_ID)) AS STATION_ID,
		LTRIM(RTRIM(STEP_NAME)) AS STEP_NAME, 
		LTRIM(RTRIM(UUT_SERIAL_NUMBER)) AS UUT_SERIAL_NUMBER, 
		LTRIM(RTRIM(START_DATE_TIME)) AS START_DATE_TIME, 
		COALESCE(HIGH_LIMIT,0) AS HIGH_LIMIT, 
		TRY_CONVERT(FLOAT,DATA) AS DATA, 
		COALESCE(LOW_LIMIT,0) AS LOW_LIMIT, 
		STATUS, 
		TOTAL_TIME, 
		LTRIM(RTRIM(COMP_OPERATOR)) AS COMP_OPERATOR
	FROM dbo.FACT_MEASURE WITH (READUNCOMMITTED) 
	WHERE UUT_SERIAL_NUMBER LIKE @uutSerialNumber
		AND START_DATE_TIME >= @startDateTime
		AND START_DATE_TIME <= @endDateTime
		AND STATION_ID LIKE @stationId 
		AND STEP_TYPE like 'NumericLimitTest%' 
		AND STATUS LIKE 'Passed%' 
		AND COMP_OPERATOR LIKE 'GELE%'
		AND (HIGH_LIMIT IS NOT NULL 
			OR LOW_LIMIT IS NOT NULL);


DECLARE db_cursor CURSOR FOR SELECT DISTINCT STEP_NAME FROM dbo.#FACT_MEASURE_TEMP;
DECLARE @STEP_NAME NVARCHAR(255);
OPEN db_cursor
FETCH NEXT FROM db_cursor INTO @STEP_NAME;
WHILE @@FETCH_STATUS = 0
BEGIN
	SELECT 
		LTRIM(RTRIM(STATION_ID)) AS STATION_ID,
		LTRIM(RTRIM(STEP_NAME)) AS STEP_NAME, 
		LTRIM(RTRIM(UUT_SERIAL_NUMBER)) AS UUT_SERIAL_NUMBER, 
		LTRIM(RTRIM(START_DATE_TIME)) AS START_DATE_TIME, 
		COALESCE(HIGH_LIMIT,0) AS HIGH_LIMIT, 
		TRY_CONVERT(FLOAT,DATA) AS DATA, 
		COALESCE(LOW_LIMIT,0) AS LOW_LIMIT, 
		STATUS, 
		TOTAL_TIME, 
		LTRIM(RTRIM(COMP_OPERATOR)) AS COMP_OPERATOR
	FROM dbo.#FACT_MEASURE_TEMP WHERE STEP_NAME like @STEP_NAME

	FETCH NEXT FROM db_cursor INTO @STEP_NAME;
END
CLOSE db_cursor;
DEALLOCATE db_cursor;

DROP TABLE dbo.#FACT_MEASURE_TEMP
END