--Disable Indexes

ALTER INDEX [IX__UUT_RESULT__START_DATE_TIME] ON [dbo].[UUT_RESULT] DISABLE
GO
ALTER INDEX [IX__STEP_RESULT__START_DATE_TIME] ON [dbo].[STEP_RESULT] DISABLE
GO
ALTER INDEX [IX__STEP_SEQCALL__START_DATE_TIME] ON [dbo].[STEP_SEQCALL] DISABLE
GO
ALTER INDEX [IX__PROP_RESULT__START_DATE_TIME] ON [dbo].[PROP_RESULT] DISABLE
GO
ALTER INDEX [IX__PROP_NUMERICLIMIT__START_DATE_TIME] ON [dbo].[PROP_NUMERICLIMIT] DISABLE
GO

---------------------------------------------------------------------------------------------

--Drop Foreign Keys

ALTER TABLE PROP_NUMERICLIMIT DROP CONSTRAINT PROP_NUMERICLIMIT_PROP_RESULT_FK
GO
ALTER TABLE PROP_RESULT DROP CONSTRAINT PROP_RESULT_STEP_RESULT_FK
GO
ALTER TABLE STEP_SEQCALL DROP CONSTRAINT STEP_SEQCALL_STEP_RESULT_FK
GO
ALTER TABLE STEP_RESULT DROP CONSTRAINT STEP_RESULT_UUT_RESULT_FK
GO

---------------------------------------------------------------------------------------------

--Add Foreign Keys

ALTER TABLE PROP_NUMERICLIMIT ADD CONSTRAINT PROP_NUMERICLIMIT_PROP_RESULT_FK FOREIGN KEY (PROP_RESULT) REFERENCES PROP_RESULT (ID)
GO
ALTER TABLE PROP_RESULT ADD CONSTRAINT PROP_RESULT_STEP_RESULT_FK FOREIGN KEY (STEP_RESULT) REFERENCES STEP_RESULT (ID)
GO
ALTER TABLE STEP_SEQCALL ADD CONSTRAINT STEP_SEQCALL_STEP_RESULT_FK FOREIGN KEY (STEP_RESULT) REFERENCES STEP_RESULT (ID)
GO
ALTER TABLE STEP_RESULT ADD CONSTRAINT STEP_RESULT_UUT_RESULT_FK FOREIGN KEY (UUT_RESULT) REFERENCES UUT_RESULT (ID)
GO

---------------------------------------------------------------------------------------------

--Rebuild Indexes

ALTER INDEX [IX__UUT_RESULT__START_DATE_TIME] ON [dbo].[UUT_RESULT] REBUILD
GO
ALTER INDEX [IX__STEP_RESULT__START_DATE_TIME] ON [dbo].[STEP_RESULT] REBUILD
GO
ALTER INDEX [IX__STEP_SEQCALL__START_DATE_TIME] ON [dbo].[STEP_SEQCALL] REBUILD
GO
ALTER INDEX [IX__PROP_RESULT__START_DATE_TIME] ON [dbo].[PROP_RESULT] REBUILD
GO
ALTER INDEX [IX__PROP_NUMERICLIMIT__START_DATE_TIME] ON [dbo].[PROP_NUMERICLIMIT] REBUILD
GO



